language: php
php:
  - "5.3"
env:
  matrix:
    - BRANCH=4.7
    - BRANCH=6.0
    - BRANCH=6.1
    - BRANCH=master
before_script: \curl --user-agent "AOE-CI" -sSL http://bit.ly/t3-ci | bash -s $BRANCH --extension="alwaysgreen" --no-tests --quiet
script: vendor/bin/phpunit --strict --verbose --testsuite alwaysgreen_all
