language: php
php:
  - "5.3"
env:
  matrix:
    - BRANCH=4.7
    - BRANCH=6.0
    - BRANCH=6.1
    - BRANCH=master
script: \curl --user-agent "AOE-CI" -sSL http://bit.ly/t3-ci | bash -s $BRANCH --extension="alwaysgreen"
